const dataList={
    "man":{
        "name":"男孩紙",
        "list":[
            {
                "name":"小明",
                "age":"15歲",
                "introduce":"普通人"
            },
            {
                "name":"大明",
                "age":"20歲",
                "introduce":"小明的哥哥"
            },
            {
                "name":"微明",
                "age":"10歲",
                "introduce":"小明的弟弟"
            }
        ]
    },
    "woman":{
        "name":"女孩紙",
        "list":[
            {
                "name":"艾莉絲",
                "age":"15歲",
                "introduce":"普通的女孩子"
            },
            {
                "name":"茱蒂",
                "age":"20歲",
                "introduce":"女子大學生"
            },
            {
                "name":"穹",
                "age":"10歲",
                "introduce":"我的羅莉妹妹"
            }
        ]
    },
    "unknow":{
        "name":"秀吉性別",
        "list":[
            {
                "name":"小雪",
                "age":"15歲",
                "introduce":"女子力高的男孩子"
            },
            {
                "name":"甘親",
                "age":"20歲",
                "introduce":"會勃起的男孩子"
            },
            {
                "name":"存在X",
                "age":"10歲",
                "introduce":"古代神話的角色"
            }
        ]
    }
}